version: '3.7'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=ahmedflow
      - N8N_BASIC_AUTH_PASSWORD=pA@d56lhHLG2688*
      - N8N_HOST=0.0.0.0
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
